@startuml
!theme plain
hide circle
skinparam classAttributeIconSize 0
skinparam class {
  IconClass false
  IconPackageStyle none
}

class User {
  - name : String
  - email : String
  - password : String
  + login() : boolean
  + logout() : void
}

class Admin {
  + deleteUser(u : User) : void
}

class Customer {
  - points : int
  + redeemPoints() : void
}

User <|-- Admin
User <|-- Customer
@enduml
